### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/breakpoints#3]
Not only to remove references to Drupal's CTools module, but also to bring it up-to-date with Backdrop's standard README template: https://github.com/backdrop-ops/module-template/blob/master/README.md

**Comment by prpwien** [comment]
Hey, I'd like to work on this issue.
Would you please assign me to it?

**Comment by ghost** [comment]
Sure thing @prpwien. Just know that for future reference you don't need to be assigned to an issue to work on it, just go for it! :smiley:
